name: Main Workflow

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push_docker_image:
    needs: test
    name: Build and push Docker image
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=schedule,pattern={{date 'YYYY-MM-DD_hh-mm-ss' tz='America/Sao_Paulo'}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CPU_COUNT=${{ vars.CPU_COUNT || '0' }}
            RANGE_NUMBER=${{ vars.RANGE_NUMBER || '68' }}
            MODS=${{ vars.MODS || '2' }}
            USE_DB=${{ vars.USE_DB || '1' }}
            NUM_RECS=${{ vars.NUM_RECS || '10000' }}
            START_MODE=${{ vars.START_MODE || '2' }}
            START_PERCENT=${{ vars.START_PERCENT || '75' }}
